import { APP_VERSION } from '../version.js';

function esc(v=''){return String(v).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));}
function n(v){return Number.isFinite(Number(v))?Number(v):'—';}
function list(v){return Array.isArray(v)?v.map(String):[];}
function dimensionPass(value,rule){if(!rule||typeof rule!=='object')return true;const mode=String(rule.mode||'ALL').toUpperCase();if(mode==='NONE')return false;if(mode==='ALL')return true;return list(rule.ids).includes(String(value??''));}
function laneFor(status){const s=String(status||'').toUpperCase();if(s==='AT_GATE'||s==='NOW')return'NOW';if(s==='ON_THE_WAY'||s==='READY')return'READY';return'WAITING';}
function arrivalMode(item){const mode=String(item.arrivalMode||item.travelMode||'UNKNOWN').toUpperCase();return['CAR','WALK','UNKNOWN'].includes(mode)?mode:'UNKNOWN';}
function arrivalModeLabel(item){const mode=arrivalMode(item);if(mode==='CAR')return'🚗 En auto';if(mode==='WALK')return'🚶 A pie';return'';}
function startedAt(item,lane){return lane==='NOW'?(item.arrivalTriggeredAt||item.updatedAt||item.requestedAt):(item.updatedAt||item.requestedAt);}
function elapsedSeconds(raw){const t=Date.parse(raw||'');return Number.isFinite(t)?Math.max(0,Math.floor((Date.now()-t)/1000)):0;}
function formatDuration(seconds){const total=Math.max(0,Math.floor(Number(seconds)||0)),h=Math.floor(total/3600),m=Math.floor((total%3600)/60),s=total%60;return h>0?`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;}
function formatDistance(value){const meters=Number(value);if(!Number.isFinite(meters)||meters<0)return'';if(meters>=1000)return`${(meters/1000).toFixed(meters>=10000?0:1)} km`;return`${Math.round(meters)} m`;}
function attentionLevel(item,lane,cfg){if(lane!=='NOW')return 0;const elapsed=elapsedSeconds(startedAt(item,lane));const maxLevel=Math.max(0,Math.min(3,Math.floor(Number(cfg.nowAttentionMaxLevel??3)||0)));if(maxLevel===0)return 0;const stepSeconds=Number(cfg.nowAttentionStepSeconds);if(Number.isFinite(stepSeconds)&&stepSeconds>0)return Math.min(maxLevel,Math.floor(elapsed/stepSeconds));const thresholds=Array.isArray(cfg.nowAttentionMinutes)&&cfg.nowAttentionMinutes.length>=3?cfg.nowAttentionMinutes:[2,5,10];if(elapsed>=Number(thresholds[2])*60)return Math.min(maxLevel,3);if(elapsed>=Number(thresholds[1])*60)return Math.min(maxLevel,2);if(elapsed>=Number(thresholds[0])*60)return Math.min(maxLevel,1);return 0;}
function attentionClass(item,lane,cfg){const level=attentionLevel(item,lane,cfg);return level?` attention-${level}`:'';}
function filteredRequests(requests,cfg){const f=cfg.filters||{},lanes=f.lanes||{};return requests.filter(item=>{const lane=laneFor(item.status);if(lanes[lane.toLowerCase()]===false)return false;return dimensionPass(item.locationId,f.locations)&&dimensionPass(item.levelId,f.levels)&&dimensionPass(item.gradeId,f.grades)&&dimensionPass(item.groupId,f.groups)&&dimensionPass(item.requestType||'PICKUP',f.requestTypes)&&dimensionPass(arrivalMode(item),f.arrivalModes);});}
function shouldShowLevel(cfg,requests){if(typeof cfg.showAcademicLevel==='boolean')return cfg.showAcademicLevel;if(Number.isFinite(Number(cfg.activeLevelCount)))return Number(cfg.activeLevelCount)>1;const configured=Array.isArray(cfg.activeLevels)?cfg.activeLevels:Array.isArray(cfg.levels)?cfg.levels.filter(level=>level?.active!==false):null;if(configured)return configured.length>1;const ids=new Set(requests.map(item=>String(item.levelId||item.levelName||item.level||'')).filter(Boolean));return ids.size>1;}
function academicLine(item,showLevel){const parts=[];if(showLevel){const level=item.levelName||item.level;if(level)parts.push(level);}const grade=item.gradeName||item.grade,group=item.groupName||item.group;if(grade)parts.push(grade);if(group)parts.push(group);return parts.join(' · ');}
function requestKey(item,index){return String(item.requestId||item.id||item.pickupRequestId||item.studentId||`row-${index}`);}
function requestCard(item,index,lane,cfg,showLevel){const academic=academicLine(item,showLevel),travel=arrivalModeLabel(item),distance=(lane==='WAITING'||lane==='READY')&&cfg.showDistance!==false?formatDistance(item.distanceMeters):'',meta=[academic,travel].filter(Boolean).join(' · '),key=requestKey(item,index),start=startedAt(item,lane),elapsed=formatDuration(elapsedSeconds(start)),attention=attentionClass(item,lane,cfg);return `<article class="queue-card lane-${lane.toLowerCase()}${attention}" data-request-id="${esc(key)}" data-lane="${lane}" data-started-at="${esc(start||'')}" data-attention-step-seconds="${esc(cfg.nowAttentionStepSeconds??'')}" data-attention-max-level="${esc(cfg.nowAttentionMaxLevel??3)}"><div class="queue-person"><h3>${esc(item.studentName||item.displayName||item.studentId||'Solicitud')}</h3>${meta?`<p>${esc(meta)}</p>`:''}</div>${distance?`<div class="queue-distance" title="Distancia estimada">${esc(distance)}</div>`:''}${lane==='NOW'?`<div class="queue-age live-delivery-timer" data-started-at="${esc(start||'')}" title="Tiempo desde llegada a AHORA">${elapsed}</div>`:''}</article>`;}
function laneSection(lane,title,subtitle,items,cfg,showLevel){const cards=items.map((item,i)=>requestCard(item,i,lane,cfg,showLevel)).join('');return `<section class="queue-lane queue-lane-${lane.toLowerCase()}"><header class="lane-heading"><div><strong>${title}</strong><span>${subtitle}</span></div><b>${items.length}</b></header><div class="lane-items">${cards||'<div class="lane-empty">Sin alumnos</div>'}</div></section>`;}
function deliveryMetricCounters(counters){const delivered=counters.deliveredToday??counters.completedToday??counters.deliveriesCompletedToday;const avg=counters.averageDeliverySeconds??counters.avgDeliverySeconds??counters.deliveryAverageSeconds;return{delivered:Number.isFinite(Number(delivered))?Number(delivered):'—',average:Number.isFinite(Number(avg))?formatDuration(Number(avg)):'—'};}
function refreshAttention(root){root?.querySelectorAll?.('.queue-card[data-lane="NOW"][data-started-at]').forEach(card=>{card.classList.remove('attention-1','attention-2','attention-3');const elapsed=elapsedSeconds(card.dataset.startedAt),step=Number(card.dataset.attentionStepSeconds),max=Math.max(0,Math.min(3,Math.floor(Number(card.dataset.attentionMaxLevel)||3)));let level=0;if(Number.isFinite(step)&&step>0)level=Math.min(max,Math.floor(elapsed/step));if(level>0)card.classList.add(`attention-${level}`);});}

export function refreshLiveTimers(root){root?.querySelectorAll?.('.live-delivery-timer[data-started-at]').forEach(node=>{node.textContent=formatDuration(elapsedSeconds(node.dataset.startedAt));});refreshAttention(root);}

export function renderControlAccess(root,model){
  const cfg=model.config||{},counters=model.counters||{},source=Array.isArray(model.pickupRequests)?model.pickupRequests:[],requests=filteredRequests(source,cfg),mode=cfg.mode||'DELIVERIES',schoolName=cfg.schoolName||cfg.instanceName||cfg.instanceKey||'Control de Acceso',gatewayBaseUrl=String(cfg.gatewayBaseUrl||'').replace(/\/$/,''),instanceLogoUrl=gatewayBaseUrl?`${gatewayBaseUrl}/instance-assets/logo`:'',location=cfg.locationName||cfg.locationId||'Sin ubicación',displayId=cfg.displayId||cfg.screenId||'Pantalla',now=new Date(),time=now.toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit'}),date=now.toLocaleDateString('es-MX',{weekday:'short',day:'2-digit',month:'short'}),showLevel=shouldShowLevel(cfg,source),deliveryMetrics=deliveryMetricCounters(counters);
  const edgeMenu=cfg.showTestControls===false?'':`<aside class="edge-menu" aria-label="Configuración rápida"><button type="button" class="edge-tab" data-edge-menu-toggle aria-label="Abrir configuración"><span></span></button><div class="edge-drawer">${[['ENTRY','Entradas'],['EXIT','Salidas'],['DELIVERIES','Entregas'],['MIXED','Mixto']].map(([value,label])=>`<button type="button" data-display-mode="${value}" class="edge-mode-button${mode===value?' active':''}">${label}</button>`).join('')}<button type="button" class="edge-mode-button edge-fullscreen-button" data-fullscreen-toggle>Pantalla completa</button></div></aside>`;
  let body='';
  if(mode==='DELIVERIES'||mode==='MIXED'){const waiting=requests.filter(r=>laneFor(r.status)==='WAITING'),ready=requests.filter(r=>laneFor(r.status)==='READY'),nowItems=requests.filter(r=>laneFor(r.status)==='NOW');body=`<section class="delivery-lanes">${laneSection('NOW','EN PUERTA (AHORA)','Listo para salir',nowItems,cfg,showLevel)}${laneSection('READY','PREPÁRATE','Ya está cerca de la escuela',ready,cfg,showLevel)}${laneSection('WAITING','EN AULA / ESPERA','Solicitud recibida',waiting,cfg,showLevel)}</section>`;}else{const heading=mode==='ENTRY'?'Entradas recientes':'Salidas recientes',cards=requests.map((r,i)=>requestCard(r,i,'WAITING',cfg,showLevel)).join('');body=`<div class="list-heading"><strong>${heading}</strong><span>${requests.length?`${requests.length} en lista`:''}</span></div><section class="queue primary-queue">${cards||'<div class="empty">Sin elementos para mostrar.</div>'}</section>`;}
  const countersHtml=(mode==='DELIVERIES'||mode==='MIXED')?`<section class="compact-counters"><div><strong>${n(counters.inside)}</strong><span>Dentro</span></div><div><strong>${deliveryMetrics.delivered}</strong><span>Entregados</span></div><div><strong>${deliveryMetrics.average}</strong><span>Promedio</span></div></section>`:`<section class="compact-counters"><div><strong>${n(counters.inside)}</strong><span>Dentro</span></div><div><strong>${n(counters.entriesToday??counters.entries)}</strong><span>Entradas</span></div><div><strong>${n(counters.exitsToday??counters.exits)}</strong><span>Salidas</span></div></section>`;
  root.innerHTML=`<section class="display-card minimal-display"><header class="topbar"><div class="instance-heading-wrap">${instanceLogoUrl?`<img class="instance-logo" src="${esc(instanceLogoUrl)}" alt="">`:''}<div class="instance-heading"><h1 class="instance-title">${esc(schoolName)}</h1><div class="screen-caption"><span class="location-caption">${esc(location)}</span></div><div class="connection-state header-connection-left"><span class="connection-dot ${model.online?'online':'offline'}"></span><small>${model.online?'Conectado':'Sin conexión'}</small></div></div></div><div class="topbar-center"><div class="clock-block"><strong>${esc(time)}</strong><span>${esc(date)}</span></div></div>${cfg.showOfficialInsideCount!==false?`<div class="topbar-right display-status-area">${countersHtml}</div>`:'<div class="topbar-right"></div>'}</header>${body}<footer class="display-footer"><div class="margin-note"><span class="brand-inline" aria-label="Nexus.Display"><span class="brand-nexus">Nexus</span><span class="brand-dot">.</span><span class="brand-display">Display</span> v${esc(APP_VERSION)}</span><span class="footer-screen-id">${esc(displayId)}</span></div></footer></section>${edgeMenu}`;
  refreshLiveTimers(root);
}
